# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Luis Carlos Pando
version: 2.72.0
author: Luis Carlos Pando
email: hey@luiscarlospando.com
description: >- # this means to ignore newlines until "baseurl:"
    Mijo (/ˈmiːhoʊ/). Punk dude. Millennial missing the old internet. Lover of music and the quirky, weird, personal web. Losing followers since 2007.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luiscarlospando.com" # the base hostname & protocol for your site, e.g. http://example.com
domain: luiscarlospando.com
capitalized_domain: LuisCarlosPando.com
blog_url: https://blog.luiscarlospando.com
mastodon_url: https://social.lol/@mijo
mastodon_username: mijo
mastodon_instance: social.lol
mastodon_feed: luiscarlospando
bluesky_url: https://bsky.app/profile/luiscarlospando.com
bluesky_username: luiscarlospando.com
omglol_username: mijo
omglol_url: https://mijo.omg.lol
x_username: mijo
x_feed: luiscarlospando
instagram_url: https://instagram.com/luiscarlospando
instagram_username: luiscarlospando
threads_username: luiscarlospando
github_username: luiscarlospando
gitlab_username: luiscarlospando
codepen_username: luiscarlospando
signal_url: https://signal.me/#eu/yXhJR9hhF1ntcOAnw5Cl6kLpsoxcYzyzFAtH-m4sLL1nZ8Ta_fBK_5lIcmQzHKyo
signal_username: luiscarlospando.85
apple_music_url: https://music.apple.com/profile/luiscarlospando
apple_music_username: luiscarlospando
spotify_username: 1269830478?si=TZzw_OTYRbWpUuk9SMW2Ow
lastfm_url: https://last.fm/user/luiscarlospando
lastfm_username: luiscarlospando
devto_username: luiscarlospando
reddit_url: https://reddit.com/u/luiscarlospando
reddit_username: luiscarlospando
twitch_username: heymijotv
twitch_purl: https://mijo.url.lol/twitch
discord_tag: heymijo
discord_profile: https://discordapp.com/users/86571896581132288/
backloggd_url: https://www.backloggd.com/u/mijo
backloggd_username: mijo
keybase_username: luiscarlospando
crucial_tracks_url: https://app.crucialtracks.org/profile/mijo
crucial_tracks_username: mijo
pi_url: https://www.pi.fyi/u/mijo
pi_referal_url: https://www.pi.fyi/subscribe/referral/mijo
spacehey_url: https://spacehey.com/mijo
spacehey_username: mijo
mode7_discord: https://discord.gg/N2m8gKw
nintendo_switch_code: SW-3920-3330-9820
m7gp_code: 0746-6549-8155
timezone: America/Chihuahua

# Build settings
markdown: kramdown
kramdown:
    parse_block_html: true
# theme: minima
plugins:
    - jekyll-info
    - jekyll-sitemap
#  - jekyll-feed
asset_pipeline:
    compress: true
info:
    production: true
future: true
include: [".well-known"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - package.json
    - package-lock.json
    - webpack.config.js
    - assets/src/
    - node-scripts/
    - TEMP_CHANGELOG.md
    - _changelog-header.md
    - .changelog-template.hbs
